Add new functions
Berkay-akbas/To-do-list pull request #2
Opened 2022-07-07 17:35 UTC by Berkay-akbas

Added new functions to add and remove tasks while updating local storage.

2022-07-07 18:33 UTC, Danieldotcomcoder requested changes
Hello @Berkay-akbas, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Professional Readme File ✔✔
- Linters are setup correctly ✔✔
- Clear and nice code ✔✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-07 18:33 UTC, Danieldotcomcoder commented on src/functions.js
> +
when I tried to add a new task, it wasn't added or updated on the screen, Kindly fix this issue 😀👍
There is something wrong because it wasn't even saved in local storage.😀👍

2022-07-08 14:06 UTC, vechicin requested changes
# Hi @Berkay-akbas ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 

 ## Required Changes ♻️

- [ ] Please make sure you remove the `print.js` file. It is an empty file so it's important you do so to keep a clean codebase.

_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 14:06 UTC, vechicin commented on src/functions.js
> +import { taskList } from './index.js'; // eslint-disable-line
When clicking a task's checkbox, the `completed` status doesn't change, therefore the `Clear completed all` button is not working. Please fix both issues.

2022-07-08 14:23 UTC, Berkay-akbas commented
@vechicin Hello, thank you for your time. This pull request was for day 3's project which was adding and removing only, should I request another review or would you be able to fix it?
Thank you for your time

2022-07-09 13:42 UTC, dasileker approved these changes
### **Hi @Berkay-akbas,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 13:58 UTC, BertrandConxy approved these changes
Hi @Berkay-akbas , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 
- no linter errors
- project works well on my pc
- good PR description
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me  @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-09 13:58 UTC, BertrandConxy commented on src/functions.js
> +import { taskList } from './index.js'; // eslint-disable-line
- [ ] [OPTIONAL] This line of code is not necessary. I would suggest you remove it to make your codebase clean😃

2022-07-11 07:24 UTC, merged